# Generated by Django 5.0.2 on 2024-02-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('content', models.TextField()),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
    ]
